services:
  mongodb:
    image: mongo:4.2
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  mock-backend:
    build: ./mock-backend
    ports:
      - "8080:8080"

volumes:
  data: