services:
  mongodb:
    image: mongo:4.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  redis:
    image: redis:5.0
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  data: